Feature read
baksohyeon/making-blog pull request #2
Opened 2022-09-21 11:56 UTC by baksohyeon

2022-09-21 15:49 UTC, kangs9d requested changes

2022-09-21 15:49 UTC, kangs9d commented on .gitignore
> +
P1: 필요 없는 공백 제거해주세요.

2022-09-21 15:49 UTC, kangs9d commented on src/blog/blog.controller.ts
> +  @Get('/:author')
P1: 이게 엔드포인트가 /blog/:author가 되는데, 실제로는 /blog/dorito 요런 식으로 엔드포인트가 나올겁니다. 특정 사용자가 가져온 블로그 목록이라는 사실을 엔드포인트로 알기 어렵습니다.
```suggestion
  @Get('/author/:author')
```
과 같은 모양이 조금 더 자연스러운 것 같습니다.

2022-09-21 15:49 UTC, kangs9d commented on src/blog/blog.service.ts
> +  async getAllBoards(): Promise<Board[]> {
P2: 함수 위치를 바꾸기만 한건 PR 리뷰에 도움이 되지 않습니다. 명확한 이유가 없다면 이렇게 동일한 로직을 바꾸지 말아주세요.
그리고 커멘트는 필요없는 것 같습니다.

2022-09-21 15:49 UTC, kangs9d commented on src/blog/blog.service.ts
> +    return this.boardRepository.find();
P0: 에러 핸들링 해주세요.

2022-09-21 15:49 UTC, kangs9d commented on src/blog/blog.service.ts
> +  async getBoardsByAuthor(author: string): Promise<Board[] | undefined> {
P2: Board[] | undefined와 같은 모양은 Union Type 이라고 하는데, 어쩔 수 없는 상황엔 몰라도 회피할 수 있으면 가능한 타입을 하나로 맞추는게 좋습니다. undefined가 나오는 경우는 Board가 하나도 없는 경우일텐데, 그럴 땐 `[] as Board[]`가 나오는게 더 일관성있지 않을까요?

2022-09-21 15:49 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    return await this.boardService.getBoardsByAuthor(author);
P1: await이 왜 필요한가요?

2022-09-22 07:53 UTC, baksohyeon commented on .gitignore
> +
넵 해결했습니다

2022-09-22 08:06 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +  @Get('/:author')
해결했습니다! !

2022-09-22 08:06 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  async getAllBoards(): Promise<Board[]> {
넹 !

2022-09-22 10:14 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    return this.boardRepository.find();
추가했습니다

2022-09-22 10:16 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  async getBoardsByAuthor(author: string): Promise<Board[] | undefined> {
해당하는 Board가 없는 경우에는 아예 리턴값 자체가 없어서 undefined가 나오지 않나여??

2022-09-22 10:16 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +    return await this.boardService.getBoardsByAuthor(author);
async 있으면 생각없이 await를 넣었습니다... ㅠㅠ 수정했습니다

2022-09-22 13:32 UTC, kangs9d commented on src/blog/blog.service.ts
> +    return this.boardRepository.find();
안되어있습니다.

2022-09-22 13:32 UTC, kangs9d commented on src/blog/blog.service.ts
> +  async getAllBoards(): Promise<Board[]> {
안되어있습니다.

2022-09-22 13:33 UTC, kangs9d commented on src/blog/blog.service.ts
> +  async getBoardsByAuthor(author: string): Promise<Board[] | undefined> {
그건 typeorm 로직이고요, 받아들이기에 `[] as Board[]`가 더 직관적이지 않냐는 말이에요.

2022-09-22 13:40 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  async getAllBoards(): Promise<Board[]> {
저는 CRUD 중 READ를 구현하는 로직끼리 한군데로 모으기 위해서 함수 위치를 옮겼습니다. 
커멘드는 지웠습니다.

2022-09-22 13:48 UTC, kangs9d commented on src/blog/blog.service.ts
> +  async getBoardsByAuthor(author: string): Promise<Board[] | undefined> {
그러면 const boards = await this.boardRepository.find(...) 한 다음, boards가 없으면 []를 반환하면 되지 않나요?

2022-09-22 13:50 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  async getAllBoards(): Promise<Board[]> {
1. github flow라는 것을 모를 때 무작정 main브랜치에 모두 진행시켰었는데 그때 create가 메인 브랜치에 있는 상태에서 각각 R, U, D를 구현하는 브랜치를 만들었습니다.
2. 그래서 각자 생성한 브랜치는 CREATE 다음에 코드를 작성하는 것이 더 좋을 것이라고 판단하였습니다.
3.  또한, 개인 학습용으로 CRUD를 만드는데 그 순서대로 코드를 작성하여 이해하기 더 용이할 것이라고 판단하였습니다.

2022-09-22 13:52 UTC, kangs9d commented on src/blog/blog.service.ts
> +  async getAllBoards(): Promise<Board[]> {
네 이해했습니다. 리졸브처리할게요

2022-09-22 13:52 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    return this.boardRepository.find();
그리고 전체 파일을 보지않고 커멘트란만 보고 자의적으로 해석하여 전혀 다른 부분을 수정하였습니다. 다음에는 이런 행동을 하지않겠다고 확실한 약속드립니다. 죄송합니다

2022-09-22 13:53 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  async getBoardsByAuthor(author: string): Promise<Board[] | undefined> {
왜 타입을 하나로 맞추는 것이 좋은가요???

2022-09-23 09:33 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    return this.boardRepository.find();
컨트롤러에서 에러핸들링 코드 추가했습니다 확인 부탁드립니다!

2022-09-23 09:33 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  async getBoardsByAuthor(author: string): Promise<Board[] | undefined> {
수정했습니다 확인 부탁드립니다

2022-09-23 12:37 UTC, kangs9d commented on src/blog/blog.service.ts
> +    return this.boardRepository.find();
컨트롤러가 그냥 throw e 하면 안되고, createBoard 보고 에러 핸들링 다시 자세히 만들어주세요.

2022-09-25 06:41 UTC, kangs9d approved these changes
LGTM

2022-09-25 06:50 UTC, merged