Feature delete
baksohyeon/making-blog pull request #3
Opened 2022-09-21 12:13 UTC by baksohyeon

2022-09-21 15:12 UTC, kangs9d requested changes

2022-09-21 15:12 UTC, kangs9d commented on .gitignore
> +
P1: 의미없는 공백은 린트에 맞지 않습니다.

2022-09-21 15:12 UTC, kangs9d commented on src/blog/blog.controller.ts
> +  @Delete('/delete/:id')
P1: 이미 delete method로 삭제라는 기능이 표현되어 있는데 또 delete가 들어간 것은 redundant 합니다. 
```suggestion
  @Delete('/:id')
```
가 더 나은 것 같습니다.

2022-09-21 15:12 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
P1: 해당 기능은 삭제 기능 구현과 무관합니다. 별도의 PR에서 다루는게 좋을 것 같습니다.

2022-09-21 15:12 UTC, kangs9d commented on src/blog/blog.service.ts
> +  createBoard(creatBoardDto: CreateBoardDto): Promise<Board> {
P1: 관련없는 변경사항은 별도의 PR에서 진행해 주세요.

2022-09-21 15:12 UTC, kangs9d commented on src/blog/blog.service.ts
> +    // return this.boardRepository.delete();
P0: deleteBoard가 아무것도 리턴하지 않으면 컨트롤러에서 리턴하는게 의미가 없습니다.
삭제시 유저가 받아야할 데이터가 뭐가 있을지 생각해보고, 해당 데이터를 리턴해주는게 좋습니다.

2022-09-21 15:20 UTC, kangs9d commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
P0: 에러 핸들링이 되어있지 않습니다. 에러 처리 해주세요.

2022-09-21 15:23 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
이미 바꿔놨는데 어떻게 별도의 PR에서 다루나요?

2022-09-21 15:24 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
이거 CRUD를 기본형을 만들고 main 브랜치에 합친 다음에 CRUD 에러핸들링 브랜치를 또 따로 팔  생각입니다.

2022-09-21 15:25 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
바꿔놓은걸 revert하거나, 원상복구하고 새 브랜치로 PR 만들어서 다뤄주세요,

2022-09-21 15:25 UTC, kangs9d commented on src/blog/blog.service.ts
> +  createBoard(creatBoardDto: CreateBoardDto): Promise<Board> {
본 PR에서 다루지 말고, 변경된 사항은 revert 하고 새 브랜치로 해당 작업 진행하라는 겁니다.

2022-09-21 15:26 UTC, kangs9d commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
기능구현은 하나가 완전하게 만들어져야 합니다. 리팩토링 한다고 해도, 기본적인 에러핸들링은 반드시 한 번에 이뤄져야 합니다.

2022-09-21 15:28 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    // return this.boardRepository.delete();
완료

2022-09-21 15:29 UTC, baksohyeon commented on .gitignore
> +
완료

2022-09-22 04:15 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +  @Delete('/delete/:id')
수정 완료했습니다!

2022-09-22 07:35 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
일단 시도하긴 했는데 제대로 된 건지 잘 모르겠습니다..

2022-09-22 07:35 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  createBoard(creatBoardDto: CreateBoardDto): Promise<Board> {
넵 진행했습니다! 잘되었나 확인 부탁드립니다 (깃허브 초초초보..)

2022-09-22 07:37 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
추가했습니다!

2022-09-22 07:59 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
작업 안됐습니다~

2022-09-22 07:59 UTC, kangs9d commented on src/blog/blog.service.ts
> +  createBoard(creatBoardDto: CreateBoardDto): Promise<Board> {
안됐습니다~

2022-09-22 08:00 UTC, kangs9d commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
```
      if (!droppedBoard) {
        this.boardRepository.delete(id);
      }
```
droppedBoard가 없으면 삭제한다는게 말이 되지 않는 로직입니다.
또한 마지막에 딱히 에러도 없는데 왜 반드시 에러를 리턴하는건가요? 에러가 특이상황이고, 리턴이 일반적인 상황임을 가정해서 코드를 짜주세요.

2022-09-22 08:07 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    await this.boardService.deleteBoard(id);
여기 await 왜있나요?

2022-09-22 08:12 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
커밋 로그 보니까 revert 잘 했는데 리버트한걸 또 리버트해서 원복됐네요.

2022-09-22 08:47 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +    await this.boardService.deleteBoard(id);
그러게요 필요가 없네요... 반영햇습니당

2022-09-22 09:10 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
리버트한걸 리버트한 커밋을 또 리버트하세영

2022-09-22 09:39 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
혹시 됐나요??

2022-09-22 13:25 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
안됐어요

2022-09-23 07:18 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  createBoard(creatBoardDto: CreateBoardDto): Promise<Board> {
dto 이름 변경 커밋을 이상하게 했습니다
dto 변경 커밋에서는 Create-Board.dto.ts 파일 내 이름만 DTO → Dto로 변경하고
service내에 있는 CreateBoardDTO 파일 명을 CreateBoardDto로 바꾼건 전혀 다른 커밋해서 진행을 하였습니다.
따라서 이 점은 pr 피드백 반영하기 힘들 것 같습니다 (git revert하면 다 날라가요 ㅠㅠ)

2022-09-23 07:25 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +    @Body() createBoardDto: CreateBoardDto,
캥즈굿님 이 부분 resolve 해도 되지 않을까 싶습니다! 혹시 더 처리할 사항 있으실까요?

2022-09-23 07:25 UTC, baksohyeon commented on src/blog/blog.service.ts
> +  createBoard(creatBoardDto: CreateBoardDto): Promise<Board> {
확인 부탁드립니다!

2022-09-23 08:09 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
확인 부탁드립니다!

2022-09-23 12:40 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
수정했습니다!!

2022-09-23 12:54 UTC, kangs9d commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
안되어있습니다.

2022-09-23 12:57 UTC, kangs9d commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
1. delete는 왜 void를 리턴하나요? 삭제하면 void 리턴해야하나요? 삭제 정보 리턴해주세요.
2. 마지막 에러 핸들링이 그냥 throw e인데, 이러면 Exception이 아니라 그냥 무조건 다 500으로 에러가 날라갑니다. 상황과 때에 맞는 적절한 에러를 선택해서 해당 에러를 보내주세요.

2022-09-23 13:02 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
다시 확인부탁드립니다

2022-09-23 13:19 UTC, kangs9d commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
리턴하기 전에 await하지 않으면 delete의 경우 try-catch에 걸리지 않고 일단 리턴한 뒤에 문제가 생길겁니다. delete 결과를 정확히 확인하고 정상값을 리턴해주세요.

2022-09-23 13:27 UTC, baksohyeon commented on src/blog/blog.service.ts
> +    const board = this.boardRepository.delete({ id });
다시 커밋했습니다 :)

2022-09-23 16:30 UTC, kangs9d commented
알람 확인용

2022-09-25 06:42 UTC, kangs9d approved these changes
LGTM

2022-09-25 06:43 UTC, merged