테스트코드 브랜치 pr 요청드립니다
baksohyeon/making-blog pull request #8
Opened 2022-10-10 06:57 UTC by baksohyeon

# Description
- 테스트코드에 대해서 개념이 전무하여 공부용으로 작성한 코드입니다.
- 테스트코드를 작성하면서 update, create api 코드를 수정하였습니다.
- 모든 테스트 코드를 짜지는 않았고, spy, mocking에 대한 개념을 이해하고 난 뒤에는 다른 구현 파트로 넘어갔습니다. 

# 참고 사항
- 기본적인 api 수정이 여기서 진행되었기 때문에, 빠르게 기본 main 브랜치로 병합하고 진도를 나가고 싶습니다. 
- 테스트 코드 제대로 짜는건 이후에 다시 할 예정입니다.

2022-10-10 14:05 UTC, kangs9d requested changes

2022-10-10 14:05 UTC, kangs9d commented on src/blog/blog.controller.ts
> +      return newBoard;
P2: 엔티티 바로 리턴하는거 안좋아요

2022-10-10 14:05 UTC, kangs9d commented on src/blog/blog.controller.ts
> +    return updatedBoard;
P1: 여기서 await 하고 리턴하는 이유가 뭐에요?

2022-10-10 14:05 UTC, kangs9d commented on src/blog/blog.service.ts
>        throw e;
P2: 에러 상황을 조금 더 구체적으로 표현해주는게 좋습니다.

2022-10-10 14:05 UTC, kangs9d commented on src/blog/blog.service.ts
> +              throw new BadRequestException('hello');
P2: hello 왜 넣었어요?

2022-10-10 14:05 UTC, kangs9d commented on src/blog/blog.service.ts
> +        return await this.boardRepository.manager.transaction(
return await 안돼요

2022-10-10 14:05 UTC, kangs9d commented on src/blog/test/blog.controller.spec.ts
> +  // describe('updateBoard', () => {
P2: 쓰지 않는 코드 지워주세요

2022-10-10 14:09 UTC, kangs9d commented on src/blog/blog.service.ts
> +            const updatedBoard = await manager.findOne(Board, {
P1: 안티패턴입니다. 기존 Orm에도 .save(entity) 로 하면 UPSERT 구현 되구요, 여기서 INSERT 안되어야 하니까 초반에 board 있는지만 확인하고 있으면 save 하면 될거에요.

2022-10-11 01:09 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +    return updatedBoard;
수정했습니다 :)

2022-10-11 01:16 UTC, baksohyeon commented on src/blog/blog.service.ts
>        throw e;
create 관련 에러핸들링은 controller 레이어 단에서 처리하였습니다.

2022-10-11 01:20 UTC, baksohyeon commented on src/blog/blog.service.ts
> +              throw new BadRequestException('hello');
수정했습니다 !

2022-10-11 01:21 UTC, baksohyeon commented on src/blog/blog.service.ts
> +            const updatedBoard = await manager.findOne(Board, {
수정했습니다

2022-10-11 01:53 UTC, baksohyeon commented on src/blog/blog.controller.ts
> +  constructor(private readonly blogService: BlogService) {}
수정햇습니당

2022-10-11 04:42 UTC, baksohyeon commented on src/blog/blog.service.ts
> +        return await this.boardRepository.manager.transaction(
일단 수정은 햇는데.. 근데 왜 그런지 궁금해서 찾아봤습니다
찾아보니 성능적 이슈에서는 크게 차이가 없고, 
1. https://stackoverflow.com/questions/43353087/are-there-performance-concerns-with-return-await

2. https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise 에서 보니까여 어차피 try catch문에서 에러핸들링할때는 저렇게 써두 된다고 하던데 제 이해가 맞나요?? 

3. https://eslint.org/docs/latest/rules/no-return-await 에서는 **return await can also be used in a try/catch statement to catch errors from another function that returns a Promise.** 라고 적혀있습니다

2022-10-11 10:20 UTC, kangs9d commented on src/blog/blog.service.ts
> +        return await this.boardRepository.manager.transaction(
저건 try - catch 블록 안에서만 쓰는걸 권장하는거에요~ 약간 내용이 다릅니다.

2022-10-11 10:20 UTC, kangs9d approved these changes
LGTM

2022-10-11 10:25 UTC, merged